version: '2.3'

networks:
  glastopf_local:

services:

# Glastopf service
  glastopf:
    build: .
    container_name: glastopf
    tmpfs:
      - /tmp/glastopf:uid=2000,gid=2000
    restart: always
    networks:
     - glastopf_local
    ports:
     - "8081:80"
    image: "ghcr.io/telekom-security/glastopf:1903"
    read_only: true
    volumes:
     - /data/glastopf/db:/tmp/glastopf/db
     - /data/glastopf/log:/tmp/glastopf/log
