version: '2.3'

networks:
  log4pot_local:

services:

# Log4pot service
  log4pot:
    build: .
    container_name: log4pot
    restart: always
    tmpfs:
     - /tmp:uid=2000,gid=2000
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - log4pot_local
    ports:
     - "80:8080"
     - "443:8080"
     - "8080:8080"
     - "9200:8080"
     - "25565:8080"
    image: "dtagdevsec/log4pot:2204"
    read_only: true
    volumes:
     - /data/log4pot/log:/var/log/log4pot/log
     - /data/log4pot/payloads:/var/log/log4pot/payloads
