version: '2.3'

networks:
  mailoney_local:

services:

# Mailoney service
  mailoney:
    build: .
    container_name: mailoney
    restart: always
    environment:
     - HPFEEDS_SERVER=
     - HPFEEDS_IDENT=user
     - HPFEEDS_SECRET=pass
     - HPFEEDS_PORT=20000
     - HPFEEDS_CHANNELPREFIX=prefix
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - mailoney_local
    ports:
     - "25:25"
    image: "dtagdevsec/mailoney:2204"
    read_only: true
    volumes:
     - /data/mailoney/log:/opt/mailoney/logs
