#networks:
#  map_local:

services:

# Map Redis Service
  map_redis:
    container_name: map_redis
    restart: always
    stop_signal: SIGKILL
    tty: true
    image: "ghcr.io/telekom-security/redis:24.04.1"
    read_only: true

# Map Web Service
  map_web:
    build: .
    container_name: map_web
    restart: always
    environment:
     - MAP_COMMAND=AttackMapServer.py
    stop_signal: SIGKILL
    tty: true
    ports:
     - "127.0.0.1:64299:64299"
    image: "ghcr.io/telekom-security/map:24.04.1"
    depends_on:
     - map_redis

# Map Data Service
  map_data:
    container_name: map_data
    restart: always
    environment:
     - MAP_COMMAND=DataServer_v2.py
#     - TPOT_ATTACKMAP_TEXT=${TPOT_ATTACKMAP_TEXT}
#     - TZ=${TPOT_ATTACKMAP_TEXT_TIMEZONE}
    stop_signal: SIGKILL
    tty: true
    image: "ghcr.io/telekom-security/map:24.04.1"
    depends_on:
     - map_redis
