version: '2.3'

services:

# Suricata service
  suricata:
    build: .
    container_name: suricata
    restart: always
    environment:
    # For ET Pro ruleset replace "OPEN" with your OINKCODE
     - OINKCODE=OPEN
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    image: "ghcr.io/telekom-security/suricata:2006"
    volumes:
     - /data/suricata/log:/var/log/suricata
