version: '2.1a'

networks:
  conpot_kamstrup_local:

services:

# Conpot service using Kamstrup Template
  conpot_kamstrup:
    container_name: conpot_kamstrup
    restart: always
    networks:
     - conpot_kamstrup_local
    ports:
     - "1025:1025"
     - "50100:50100"
    image: "dtagdevsec/conpot:1710"
    volumes:
     - /data/conpot_kamstrup/log:/var/log/conpot_kamstrup
