version: '2.1'

networks:
  conpot_IEC104_local:

services:

# Conpot service using IEC104 Template
  conpot_IEC104:
    container_name: conpot_IEC104
    restart: always
    networks:
     - conpot_IEC104_local
    ports:
     - "2404:2404"
    image: "dtagdevsec/conpot:1710"
    volumes:
     - /data/conpot_IEC104/log:/var/log/conpot_IEC104
