version: '2.1'

networks:
  conpot_default_local:

services:

# Conpot service using Default Siemens S7-200 Template
  conpot_default:
    container_name: conpot_default
    restart: always
    networks:
     - conpot_default_local
    ports:
     - "102:102"
     - "502:502"
     - "2404:2404"
     - "47808:47808"
     - "161:161/udp"
    image: "dtagdevsec/conpot:1710"
    volumes:
     - /data/conpot_default/log:/var/log/conpot_default
